Controllers/AppointmentsController.cs
using Doctor_Appointment.Models;
using Doctor_Appointment.Repo;
using Doctor_Appointment.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Doctor_Appointment.Controllers
{
    [Authorize]
    public class AppointmentsController : Controller
    {
        private readonly IAppointmentRepo _appointmentRepo;
        private readonly IDoctorRepo _doctorRepo;
        private readonly IPatientRepo _petientRepo;

        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _user;



        public AppointmentsController(IAppointmentRepo appointmentRepo, SignInManager<IdentityUser> manager,
            UserManager<IdentityUser> user, IDoctorRepo doctorRepo, IPatientRepo petientRepo)
        {
            _appointmentRepo = appointmentRepo;
            _doctorRepo = doctorRepo;
            _signInManager = manager;
            _user = user;
            _petientRepo = petientRepo;

        }

        // GET: Appointments

        [Authorize(Roles = "Patient")]
        public IActionResult Index()
        {
            int patId;
            if (_signInManager.IsSignedIn(User))
            {
                var userIdentity = User.Claims.First().Value;
                var patient = _petientRepo.GetAllIQuarable().Where(p => p.IdentityId == userIdentity).FirstOrDefault();
                if (patient == null)
                    return NotFound();
                patId = patient.PatientID;
            }
            else
                return BadRequest();
            var appointments = _appointmentRepo.GetAllQuerable().Where(p => p.PatientID == patId).Include(p => p.Doctor).Include(p => p.Day).ToList();

            return View(appointments);

        }


        [Authorize(Roles = "Doctor")]
        public IActionResult DoctorAppointmentList()
        {
            int DocId;
            if (_signInManager.IsSignedIn(User))
            {
                var userIdentity = User.Claims.First().Value;
                var Doctor = _doctorRepo.GetAll().Where(p => p.IdentityId == userIdentity).FirstOrDefault();
                if (Doctor == null)
                    return NotFound();
                DocId = Doctor.DoctorID;
            }
            else
                return BadRequest();
            var appointments = _appointmentRepo.GetAllQuerable().Where(p => p.DoctorID == DocId).Include(p => p.Patient).Include(p => p.Day).ToList();

            return View(appointments);

        }

        [Authorize(Roles = "Patient")]
        public IActionResult SelectDoctor()
        {

            return View("SelectDoctor", _doctorRepo.GetAll());
        }
        [Authorize(Roles = "Patient")]

        public IActionResult Create(int Id)
        {
            if (Id <= 0)
                return BadRequest();
            var Doc = _doctorRepo.GetByIdWithIncludingDays(Id);
            if (Doc is null)
                return NotFound();

            var availableDays = Doc.AvailableDays.Where(d => d.Date >= DateTime.Now && d.BookedAppointments < d.countAppointment);
            var appointment = new AppoinmentVM();
            appointment.DocId = Id;
            appointment.Price = Doc.Price;
            appointment.DocName = Doc.FullName;
            appointment.HomeExaminiation = Doc.HomeExamination;
            foreach (var d in availableDays)
            {
                appointment.AvailableDays.Add(d.Dayid, d.ToString());
            }
            return View(appointment);
        }
        [Authorize(Roles = "Patient")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AppoinmentVM appointment)
        {
            if (!ModelState.IsValid)
            {
                var Doc = _doctorRepo.GetByIdWithIncludingDays(appointment.DocId);
                if (Doc is null)
                    return NotFound();

                var availableDays = Doc.AvailableDays;
                foreach (var d in availableDays)
                {
                    appointment.AvailableDays.Add(d.Dayid, d.ToString());
                }
                return View(appointment);

            }
            //get patient id using Identity
            if (_signInManager.IsSignedIn(User))
            {
                var userIdentity = User.Claims.First().Value;
                var patient = _petientRepo.GetAllIQuarable().Where(p => p.IdentityId == userIdentity).FirstOrDefault();
                if (patient == null)
                    return NotFound();
                appointment.PatienteId = patient.PatientID;
            }
            else
                return BadRequest();
            //check if docter is exist
            var doctor = _doctorRepo.GetById(appointment.DocId);
            if (doctor == null)
                return BadRequest();
            //if this appointment is already boocked
            var isBoocked = _appointmentRepo.IsBoocked(appointment);
            if (isBoocked == true)
            {
                ModelState.AddModelError("", "You already blocked in this day ");
                //get available days and to appointmenViewModel
                var Doc = _doctorRepo.GetByIdWithIncludingDays(appointment.DocId);
                var availableDays = Doc.AvailableDays.Where(d => d.BookedAppointments < d.countAppointment);
                foreach (var d in availableDays)
                {
                    appointment.AvailableDays.Add(d.Dayid, d.ToString());
                }
                return View(appointment);
            }

            // check if Doctor available to Home Exmamination whene user choose  HomeExmamination
            if (appointment.AppointmentType.Equals(AppointmentType.HomeExamination))
            {
                if (!doctor.HomeExamination)
                {
                    ModelState.AddModelError("AppointmentType", "Ooh!Home Examination Not available of this doctor");
                    //get available days and to appointmenViewModel
                    var Doc = _doctorRepo.GetByIdWithIncludingDays(appointment.DocId);
                    var availableDays = Doc.AvailableDays.Where(d => d.BookedAppointments < d.countAppointment);
                    foreach (var d in availableDays)
                    {
                        appointment.AvailableDays.Add(d.Dayid, d.ToString());
                    }
                    return View(appointment);
                }
            }

            _appointmentRepo.Insert(appointment);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Patient")]
        public IActionResult Delete(int id)
        {
            if (id <= 0)
                return BadRequest();
            var appo = _appointmentRepo.GetById(id);
            if (appo == null)
                return NotFound();
            var result = _appointmentRepo.Delete(id);
            return result ? Ok() : BadRequest();
        }


    }
}

Controllers/DoctorsController.cs
using Doctor_Appointment.Models;
using Doctor_Appointment.Repo;
using Doctor_Appointment.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using System.Text;

namespace Doctor_Appointment.Controllers
{
	[Authorize(Roles = "Admin")]
	public class DoctorsController : Controller
	{
		//public ApplicationDbContext Context { get; }
		private readonly IDoctorRepo _doctor;
		private readonly UserManager<IdentityUser> _userManager;
		private readonly SignInManager<IdentityUser> _signInManager;
		public DoctorsController(IDoctorRepo doctor, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
		{

			_doctor = doctor;
			_userManager = userManager;
			_signInManager = signInManager;
		}

		[AllowAnonymous]
		// GET: DoctorsController
		public ActionResult Index()
		{
			return View(_doctor.GetAll());
		}

		// GET: DoctorsController/Details/5
		[AllowAnonymous]
		public ActionResult Details(int id)
		{
			if (id <= 0)
				return BadRequest();
			var doctor = _doctor.GetByIdWithIncludingDays(id);

			if (doctor is null)
				return NotFound();
			return View(doctor);
		}


		// GET: DoctorsController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: DoctorsController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create(CreateDoctoreVM doc)
		{
			if (!ModelState.IsValid)
			{
				return View(doc);
			}
			var DoctorName = _doctor.GetAll().Where(d => d.FullName == doc.FullName && d.Specialist == doc.Specialist).FirstOrDefault();
			if (DoctorName != null)
			{
				ModelState.AddModelError("FullName", "This name already exist");
				return View(doc);
			}

			var registResult = await RegiterForDoctor(new DoctorRegistrationVM()
			{
				Email = doc.Email,
				Password = doc.Password,
			});
			if (registResult.IsRegister is false)
			{
				ModelState.AddModelError("", registResult.Result);
				return View(doc);
			}
			doc.IdentityId = registResult.Result;
			var DoctorID = _doctor.Insert(doc);


			return RedirectToAction("Create", "DailyAvailbilities", new { docId = DoctorID });

		}

		// GET: DoctorsController/Edit/5
		public ActionResult Edit(int id)
		{
			if (id <= 0)
				return BadRequest();
			var doctor = _doctor.GetById(id);
			if (doctor is null)
				return NotFound();

			var doctorVM = new EditDoctorVM()
			{
				Id = doctor.DoctorID,
				FullName = doctor.FullName,
				Gender = doctor.Gender,
				Specialist = doctor.Specialist,
				Degree = doctor.Degree,
				Description = doctor.Description,
				Clinic_Location = doctor.Clinic_Location,
				Clinic_PhonNum = doctor.Clinic_PhonNum,
				Price = doctor.Price,
				HomeExamination = doctor.HomeExamination,


			};

			return View(doctorVM);

		}

		// POST: DoctorsController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(EditDoctorVM doctorVM)
		{
			if (!ModelState.IsValid)
			{
				return View(doctorVM);
			}
			var DoctorName = _doctor.GetAll().Where(d => d.FullName == doctorVM.FullName && d.Specialist == doctorVM.Specialist && d.DoctorID != doctorVM.Id).FirstOrDefault();
			if (DoctorName != null)
			{
				ModelState.AddModelError("FullName", "This name already exist");
				return View(doctorVM);
			}

			_doctor.Update(doctorVM);
			return RedirectToAction("Details", new { id = doctorVM.Id });

		}

		//GET: DoctorsController/Delete/5
		public async Task<IActionResult> DeleteAsync(int id)
		{
			if (id <= 0)
				return BadRequest();
			var doc = _doctor.GetById(id);
			if (doc is null)
				return NotFound();
			var result = _doctor.Delete(id);
			if (result)
			{
				var user = await _signInManager.UserManager.FindByIdAsync(doc.IdentityId);
				if (user is not null)
					await _signInManager.UserManager.DeleteAsync(user);
				return RedirectToAction(nameof(Index));

			}
			return BadRequest();
		}
		//Register doctor In user table with doctor role
		private async Task<ReturnRegisterDocVm> RegiterForDoctor(DoctorRegistrationVM newUser)
		{

			ApplicationUser userModel = new();
			userModel.UserName = new MailAddress(newUser.Email).User;


			userModel.Email = newUser.Email;
			userModel.PasswordHash = newUser.Password;
			StringBuilder stringBuilder = new StringBuilder();


			IdentityResult result = await _userManager.CreateAsync(userModel, userModel.PasswordHash);

			if (result.Succeeded)
			{
				await _userManager.AddToRoleAsync(userModel, "Doctor");

				stringBuilder.Append(userModel.Id);
				return new ReturnRegisterDocVm() { IsRegister = true, Result = stringBuilder.ToString() };

			}
			else
			{
				foreach (var error in result.Errors)
				{
					stringBuilder.AppendLine(error.Description);
				}
			}

			return new ReturnRegisterDocVm() { IsRegister = false, Result = stringBuilder.ToString() };

		}


	}
}

Controllers/PatientsController.cs
using Doctor_Appointment.Models;
using Doctor_Appointment.Repo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Doctor_Appointment.Controllers
{
    [Authorize]

    public class PatientsController : Controller
    {
        private readonly IPatientRepo _patientRepo;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _user;

        public PatientsController(IPatientRepo patientRepo, SignInManager<IdentityUser> manager, UserManager<IdentityUser> user)
        {
            _patientRepo = patientRepo;
            _signInManager = manager;
            _user = user;
        }

        // GET: Patients
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(_patientRepo.GetAll());
        }



        [Authorize(Roles = "Patient")]

        // GET: Patients/Create
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Patient")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Patient patient)
        {
            if (ModelState.IsValid)
            {
                if (_signInManager.IsSignedIn(User))
                {
                    var userIdentity = User.Claims.First().Value;
                    patient.IdentityId = userIdentity;
                }
                else
                {
                    return BadRequest();
                }
                var DoctorName = _patientRepo.GetAllIQuarable().Where(p => p.FullName == patient.FullName).FirstOrDefault();
                if (DoctorName != null)
                {
                    ModelState.AddModelError("FullName", "This name already exist");
                    return View(patient);
                }
                _patientRepo.Insert(patient);

                return RedirectToAction("Index", "Home");
            }
            return View(patient);
        }

        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> UncomplatedRegister()
        {

            if (_signInManager.IsSignedIn(User))
            {
                var userIdentity = User.Claims.First().Value;
                var user = await _signInManager.UserManager.FindByIdAsync(userIdentity);
                if (user is not null)
                    await _signInManager.UserManager.DeleteAsync(user);
                await _signInManager.SignOutAsync();
            }
            return RedirectToAction("Index", "Home");

        }


        // GET: Patients/Delete/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> DeleteAsync(int id)
        {
            if (id <= 0) return BadRequest();

            var patient = _patientRepo.GetById(id);

            if (patient is null)
                return NotFound();
            var result = _patientRepo.Delete(id);
            if (result)
            {
                var user = await _signInManager.UserManager.FindByIdAsync(patient.IdentityId);
                if (user is not null)
                    await _signInManager.UserManager.DeleteAsync(user);
                return Ok();
            }
            return BadRequest();
        }



    }
}

Views/Shared/_AllDoctorsPartial.cshtml
@using System.ComponentModel;
@model IEnumerable<Doctor_Appointment.Models.Doctor>

<div class="col-12 text-center  mb-5">
    <div class="btn-group btn-group-toggle " data-toggle="buttons">
        <label class="btn active ">
            <input type="radio" name="shuffle-filter" value="all" checked="checked" />All Department
        </label>
        @{
            foreach (Spectialist specialization in Enum.GetValues(typeof(Spectialist)))
            {
                DescriptionAttribute[] attributes = (DescriptionAttribute[])specialization
                .GetType()
                .GetField(specialization.ToString())
                .GetCustomAttributes(typeof(DescriptionAttribute), false);

                string description = attributes.Length > 0 ? attributes[0].Description : specialization.ToString();

                <label class="btn ">
                    <input type="radio" name="shuffle-filter" value="@description" />@description
                </label>
            }
        }
    </div>
</div>

<div class="row shuffle-wrapper portfolio-gallery">
    @{
        foreach (var doctor in Model)
        {
            <div class="col-lg-3 col-sm-6 col-md-6 mb-4 shuffle-item"
                 data-groups="[&quot;@doctor.GetSpecializationDescription()&quot;]">
                <div class="position-relative doctor-inner-box">
                    <div class="doctor-profile">
                        <div class="doctor-img">
                            <img src=@doctor.GetImage() alt="doctor-image" class="img-fluid w-100">
                        </div>
                    </div>
                    <div class="content mt-3">
                        <h4 class="mb-0"><a asp-area="" asp-controller="Doctors" asp-action="Details" asp-route-id="@doctor.DoctorID">@doctor.FullName</a></h4>
                        <p>@doctor.GetSpecializationDescription()</p>
                    </div>
                </div>
            </div>
        }
    }
</div>

Views/Shared/_ExminationDayList.cshtml
@model IEnumerable<Doctor_Appointment.Models.DailyAvailbility>

<div class="section-title">

	<table class="table">
		<thead>
			<tr>
				<th>
					Day
				</th>
				<th>
					Date
				</th>
				<th>
					Start Time
				</th>
				<th>
					End Time
				</th>
				<th>
					Count Appointment
				</th>
				@if (User.IsInRole("Admin") || User.IsInRole("Doctor"))
				{
					<th>
					</th>
					<th>
					</th>
					<th>
					</th>
				}
				


			</tr>
		</thead>
		<tbody>
			@foreach (var Appoint in Model)
			{
				<tr>
					<td>
						@Appoint.Date.DayOfWeek.ToString()
					</td>


					<td>
						@Appoint.Date.Date.ToString("m")
					</td>
					<td>
						@Appoint.StartTime.ToString(@"hh\:mm")

					</td>
					<td>
						@Appoint.EndTime.ToString(@"hh\:mm")

					</td>
					<td>
						@Appoint.countAppointment

					</td>
					@if(User.IsInRole("Admin") || User.IsInRole("Doctor"))
					{
						<td>

							<a asp-controller="DailyAvailbilities" asp-action="DayAppointments" asp-route-id="@Appoint.Dayid" class="edit">Edit</a>

						</td>
						<td>
							<a asp-controller="DailyAvailbilities" asp-action="DayAppointments" asp-route-dayId="@Appoint.Dayid" class="edit">Appointments</a>

						</td>
						<td>
							<a href="javaScript:;" class="js-delete" data-id="@Appoint.Dayid">Delete</a>
						</td>
					}
				



				</tr>

			}
		</tbody>
	</table>

</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="description" content="Orbitor,business,company,agency,modern,bootstrap4,tech,software">
    <meta name="author" content="themefisher.com">

    <title>Novena- Health & Care Medical template</title>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <!-- bootstrap.min css -->
    <link rel="stylesheet" href="~/plugins/bootstrap/css/bootstrap.min.css">
    <!-- Icon Font Css -->
    <link rel="stylesheet" href="~/plugins/icofont/icofont.min.css">
    <!-- Slick Slider  CSS -->
    <link rel="stylesheet" href="~/plugins/slick-carousel/slick/slick.css">
    <link rel="stylesheet" href="~/plugins/slick-carousel/slick/slick-theme.css">
    <link href="https://unpkg.com/gijgo@1.9.14/css/gijgo.min.css" rel="stylesheet" type="text/css" />



    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />

    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/css/style.css">
   
</head>


<body id="top">

    <header>
     
        <nav class="navbar navbar-expand-lg navigation" id="navbar">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/Logo.png" alt="" class="img-fluid" width="100" height="100">
                </a>

                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarmain"
                        aria-controls="navbarmain" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icofont-navigation-menu"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarmain">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                      

                      
                        @if (SignInManager.IsSignedIn(User))
                        {

                            if (User.IsInRole("Patient"))
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">Your Appointments</a>
                                </li>
                            }
                            if (User.IsInRole("Doctor"))
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="DoctorAppointmentList"> Appointments</a>

                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="DailyAvailbilities" asp-action="Index">Exmination days</a>

                                </li>
                            }
                            if (User.IsInRole("Admin"))
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="Index">All Doctors</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Patients" asp-action="Index">Patients</a>
                                </li>
                            }

                        }
                        <li class="nav-item">
                            <a  class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">About Us</a>
                        </li>

                       
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div>
        @RenderBody()
    </div>

    <!-- footer Start -->
    <footer class="footer section gray-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 mr-auto col-sm-6">
                    <div class="widget mb-5 mb-lg-0">
                        <div class="logo mb-4">
                            <img src="~/images/Logo.png" alt="" class="img-fluid">
                        </div>
                        <p>
                            Tempora dolorem voluptatum nam vero assumenda voluptate, facilis ad eos obcaecati tenetur
                            veritatis eveniet distinctio possimus.
                        </p>

                        <ul class="list-inline footer-socials mt-4">
                            <li class="list-inline-item">
                                <a href="">
                                    <i class="icofont-facebook"></i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="">
                                    <i class="icofont-twitter"></i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="">
                                    <i class="icofont-linkedin"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

              

                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="widget widget-contact mb-5 mb-lg-0">
                        <h4 class="text-capitalize mb-3">Get in Touch</h4>
                        <div class="divider mb-4"></div>

                        <div class="footer-contact-block mb-4">
                            <div class="icon d-flex align-items-center">
                                <i class="icofont-email mr-3"></i>
                                <span class="h6 mb-0">Support Available for 24/7</span>
                            </div>
                            <h4 class="mt-2"><a href="tel:+23-345-67890">Support@email.com</a></h4>
                        </div>

                        <div class="footer-contact-block">
                            <div class="icon d-flex align-items-center">
                                <i class="icofont-support mr-3"></i>
                                <span class="h6 mb-0">Mon to Fri : 08:30 - 18:00</span>
                            </div>
                            <h4 class="mt-2"><a href="tel:+23-345-67890">+23-456-6588</a></h4>
                        </div>
                    </div>
                </div>
            </div>

            <div class="footer-btm py-4 mt-5">
                <div class="row align-items-center justify-content-between">
                    <div class="col-lg-6">
                        <div class="copyright">
                            &copy; Copyright Reserved to <span class="text-color">Novena</span> by <a href="https://themefisher.com/" target="_blank">Themefisher</a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="subscribe-form text-lg-right mt-5 mt-lg-0">
                            <form action="#" class="subscribe">
                                <input type="text" class="form-control" placeholder="Your Email address">
                                <a @*href="#"*@ class="btn btn-main-2 btn-round-full">Subscribe</a>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <a class="backtop js-scroll-trigger" href="#top">
                            <i class="icofont-long-arrow-up"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
   
    <!-- Main jQuery -->
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
  
    <!-- Bootstrap 4.3.2 -->
    <script src="~/plugins/bootstrap/js/popper.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/plugins/counterup/jquery.easing.js"></script>
   
    <!-- Slick Slider -->
    <script src="~/plugins/slick-carousel/slick/slick.min.js"></script>
    <!-- Counterup -->
    <script src="~/plugins/counterup/jquery.waypoints.min.js"></script>

    <script src="~/plugins/shuffle/shuffle.min.js"></script>
    <script src="~/plugins/counterup/jquery.counterup.min.js"></script> 

    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/script.js"></script>
    <script src="~/js/contact.js"></script>

    @await RenderSectionAsync("Scripts", required: false)







</body>
</html>